const channels = [
  'TimeSpanInSec',
  'Digital_PowerManagementRelay_Out_1',
  'EnergyReal_WAC_Sum_Produced',
  'InverterEvents',
  'InverterErrors',
  'Current_DC_String_1',
  'Current_DC_String_2',
  'Voltage_DC_String_1',
  'Voltage_DC_String_2',
  'Temperature_Powerstage',
  'Voltage_AC_Phase_1',
  'Voltage_AC_Phase_2',
  'Voltage_AC_Phase_3',
  'Current_AC_Phase_1',
  'Current_AC_Phase_2',
  'Current_AC_Phase_3',
  'PowerReal_PAC_Sum',
  'EnergyReal_WAC_Minus_Absolute',
  'EnergyReal_WAC_Plus_Absolute',
  'Meter_Location_Current',
  'Temperature_Channel_1',
  'Temperature_Channel_2',
  'Digital_Channel_1',
  'Digital_Channel_2',
  'Radiation',
  'Digital_PowerManagementRelay_Out_1',
  'Hybrid_Operating_State',
  'StateOfCharge_Relative'
]

module.exports = channels
